### ISSUE TITLE
GitHub solution is returning an error message

### ISSUE THREAD

**Issue by DanielG808** [learn-co-curriculum/dsc-functions-with-arguments-lab#3]
## Link to Canvas
https://w-danie-ds-course-prep-b1aa04d1488143ea9e5ea92c01e21698.flatironschool.saturnenterprise.io/notebooks/workspace/flatiron-curriculum/Prep/dsc-functions-with-arguments-lab/index.ipynb

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [x ] Other (explain below)

I have copied a solution from github directly into the Jupyter notebook lab, restarted the Kernel, and executed all prerequisite cells, but I am still receiving an error when I execute the provided solution.

### Source
def is_better(restaurant, alternative):
    return restaurant_rating(restaurant) > restaurant_rating(alternative)

is_better(frontier_restaurant, fork_fig)

4.0
4.5

### Concern
The above code references a function "restaurant_rating()" within the function "is_better()". When executed, "is_better()" only returns the values of the function "restaurant_rating()" instead of comparing the values to get a boolean output. Again, the solution pasted in this report was taken directly from the GitHub solution tab on this lab.

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ x] Saturn Cloud from Canvas

**Comment by jessepisel** [comment]
Thanks for opening this issue @DanielG808 :wave:. I have run through the solution branch and cannot replicate the issue you had above on Saturn Cloud. Make sure that you have defined the `restaurant_rating` function as:
```python
def restaurant_rating(restaurant):
    return restaurant['rating']
```

which returns a numeric values. If you then use that inside the `is_better` function it will return a boolean from the comparison of the two numeric values.

```python
def is_better(restaurant, alternative):
    return restaurant_rating(restaurant) > restaurant_rating(alternative)
```

Please let me know what other questions you have. I am going to close this issue at this time.
